---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- persistent-volume-claim.yaml
- deployment.yaml
- service.yaml

namespace: mariadb-v10-4

commonLabels:
  app: mariadb-v10-4