apiVersion: v1
kind: Pod
metadata:
  name: pod-print-env
spec:
  containers:
    - name: test
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: config-map
  restartPolicy: Never