---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ./mongo/persistent-volume-claim.yaml
- ./elasticsearch/persistent-volume-claim.yaml
- persistent-volume-claim.yaml
- cluster-role.yaml
- cluster-role-biding.yaml
- ./elasticsearch/deployment.yaml
- ./elasticsearch/service.yaml
- ./mongo/deployment.yaml
- ./mongo/service.yaml
- service-account.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- ./fluentd/service-account.yaml
- ./fluentd/cluster-role.yaml
- ./fluentd/cluster-role-biding.yaml
- ./fluentd/daemon-set.yaml

namespace: graylog

commonLabels:
  app: graylog