apiVersion: v1
kind: Service
metadata:
  namespace: graylog
  labels:
    service: mongo
  name: mongo
spec:
  # clusterIP: None
  type: ClusterIP
  ports:
  - name: headless
    port: 27017
    targetPort: 0
  selector:
    service: mongo
status:
  loadBalancer: {}