apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: graylog
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - endpoints
  verbs:
  - get
  - list
  - watch