apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graylog
  namespace: graylog
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch