apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: graylog
  namespace: graylog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: graylog
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: graylog
  namespace: graylog