apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  strategy: {}
  template:
    metadata:
      labels:
        app: graylog
    spec:
      serviceAccount: graylog
      containers:
      - env:
        # - name: GRAYLOG2_REST_ENABLE_CORS
        #   value: "true"
        - name: GRAYLOG_HTTP_ENABLE_CORS
          value: "true"
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: http://graylog.ronsal.com.br/api
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: "http://elasticsearch.graylog.svc.cluster.local:9200"
        - name: ELASTICSEARCH_DISCOVERY_ZEN_PING_MULTICAST_ENABLED
          value: "false"
        - name: ELASTICSEARCH_DISCOVERY_ZEN_PING_UNICAST_HOSTS
          value: "elasticsearch.graylog.svc.cluster.local:9300"
        # - name: GRAYLOG_PASSWORD_SECRET
        #   value: Rt6Z0aJvBZL7d7yQUIGzaL8DKwlybjYznnjlsvcowDqV9PXaUy4S19aeh3Gl2NO1sRZYXVxiXipOcqCxUgcrMV6nvYgp9CNs
        # - name: GRAYLOG_ROOT_PASSWORD_SHA2
        #   value: fa72460a30af5bab75ba59012e8a812cf5436c49b1d8412af8cc8c656346ae18
        image: docker.io/graylog2/server:2.3.0-1 
        #image: graylog/graylog:3.0
        # Repositório oficial - docker.io/graylog2/server:2.3.0-1
        name: graylog
        ports:
        - containerPort: 9000
        - containerPort: 12201
        resources: {}

        volumeMounts:
        - name: graylog-volume
          mountPath: /opt/graylog/data

    #/opt/graylog/data \
    #/opt/graylog/data/journal \
    #/opt/graylog/data/log \
    #/opt/graylog/data/config \
    #/opt/graylog/data/plugin \
    #/opt/graylog/data/data

      restartPolicy: Always

      volumes:
      - name: graylog-volume
        persistentVolumeClaim:
          claimName: graylog-pvc

status: {}