
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami5
  labels:
    allow.http: "true"
    application: whoami5
spec:
  replicas: 2
  selector:
    matchLabels:
      application: whoami5
  template:
    metadata:
      labels:
        application: whoami5
    spec:
      containers:
      - name: whoami5
        image: jwilder/whoami
        ports:
        - containerPort: 8000
        securityContext:
          privileged: true


---
apiVersion: v1
kind: Service
metadata:
  name: whoami5
spec:
  type: ClusterIP
  ports:
  - port: 80 # Porta a ser exposta pelo SERVICE
    targetPort: 8000 # Porta que a aplicação está rodando no POD
  selector:
    application: whoami5


---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: whoami5
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  tls:
    - secretName: rancher-ronsal-com-br-tls
  rules:
    - host: app.ronsal.com.br
      http:
        paths:
          - backend:
              service:
                name: whoami5
                port:
                  number: 80
            path: /
            pathType: Prefix



