apiVersion: v1
kind: Service
metadata:
  namespace: graylog
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  type: ClusterIP
  ports:
  - name: headless
    port: 9200
    targetPort: 0
  selector:
    service: elasticsearch
status:
  loadBalancer: {}